### ISSUE TITLE
V2 Addon conversion?

### ISSUE THREAD

**Issue by NullVoxPopuli** [chriskrycho/ember-async-data#351]
I'd like to convert this to a v2 addon, and I'd like to propose two paths:
1. [all at once](https://github.com/emberjs/ember-string/pull/345)
2. 4 step process, as outlined on [`@ember/string`](https://github.com/emberjs/ember-string/pull/345#issuecomment-1191943924)
   1. switch to pnpm
   2. convert to monorepo
   3. create test-app 
   4. move tests from v1 addon to test-app
   5. convert to v2 addon
  
  Idk how much ya'll are familiar with v2 addon conversion, but the all at once PR, while way easier / faster, seems to scare folks not so familiar with the process. :sweat_smile:

**Comment by chriskrycho** [comment]
I’ve landed a few. A PR is welcome (including if @sergeastapov wants to do one of his amazing passes that way)! Just not yet at the top of the priority list to do myself.

**Comment by chriskrycho** [comment]
And to clarify: option (1) is totally fine!

**Comment by chriskrycho** [comment]
…fair warning: we need to get CI passing against Ember v4 first. It should be *super* easy, it just hasn’t, again, been at the top of the priority list yet. (It will be next week, though, b/c we’ll want it unblocked for work.)

**Comment by SergeAstapov** [comment]
@chriskrycho sure, would be glad to. might be good to starting point to warm and get little more active with contribution 🤪

**Comment by SergeAstapov** [comment]
for the info, I'm always in favor of path 2 as it's easier to handle one thing at a time and less chance to break things accidentally

**Comment by SergeAstapov** [comment]
I've started with making CI green, then doing slated breaking changes (dropping older Node.js + Ember versions support) and next thing will work on monorepoification followed by v2 addon conversion

**Comment by SergeAstapov** [comment]
v0.7.0 published to npm
